FROM crazymax/xgo:1.19.2
RUN curl https://dl.google.com/go/go1.19.4.linux-amd64.tar.gz -o go.linux-amd64.tar.gz
RUN rm -rf /usr/local/go
RUN tar -zxvf go.linux-amd64.tar.gz -C /usr/local

# docker build -t crazymax/xgo:1.19.4 .
