// @generated Do not edit this file, which is automatically generated by the generator.

package dbschema

import (
	"fmt"

	"time"

	"github.com/webx-top/db"
	"github.com/webx-top/db/lib/factory"
	"github.com/webx-top/echo"
	"github.com/webx-top/echo/param"
)

type Slice_ForeverProcess []*ForeverProcess

func (s Slice_ForeverProcess) Range(fn func(m factory.Model) error) error {
	for _, v := range s {
		if err := fn(v); err != nil {
			return err
		}
	}
	return nil
}

func (s Slice_ForeverProcess) RangeRaw(fn func(m *ForeverProcess) error) error {
	for _, v := range s {
		if err := fn(v); err != nil {
			return err
		}
	}
	return nil
}

// ForeverProcess 持久进程
type ForeverProcess struct {
	base    factory.Base
	objects []*ForeverProcess

	Id           uint   `db:"id,omitempty,pk" bson:"id,omitempty" comment:"ID" json:"id" xml:"id"`
	Uid          uint   `db:"uid" bson:"uid" comment:"添加人ID" json:"uid" xml:"uid"`
	Name         string `db:"name" bson:"name" comment:"名称" json:"name" xml:"name"`
	Command      string `db:"command" bson:"command" comment:"命令" json:"command" xml:"command"`
	Workdir      string `db:"workdir" bson:"workdir" comment:"工作目录" json:"workdir" xml:"workdir"`
	Env          string `db:"env" bson:"env" comment:"环境变量" json:"env" xml:"env"`
	Args         string `db:"args" bson:"args" comment:"命令参数" json:"args" xml:"args"`
	Pidfile      string `db:"pidfile" bson:"pidfile" comment:"PID记录文件" json:"pidfile" xml:"pidfile"`
	Logfile      string `db:"logfile" bson:"logfile" comment:"日志记录文件" json:"logfile" xml:"logfile"`
	Errfile      string `db:"errfile" bson:"errfile" comment:"错误记录文件" json:"errfile" xml:"errfile"`
	Respawn      uint   `db:"respawn" bson:"respawn" comment:"重试次数(进程被外部程序结束后自动启动)" json:"respawn" xml:"respawn"`
	Delay        string `db:"delay" bson:"delay" comment:"延迟启动(例如1ms/1s/1m/1h)" json:"delay" xml:"delay"`
	Ping         string `db:"ping" bson:"ping" comment:"心跳时间(例如1ms/1s/1m/1h)" json:"ping" xml:"ping"`
	Pid          int    `db:"pid" bson:"pid" comment:"PID" json:"pid" xml:"pid"`
	Status       string `db:"status" bson:"status" comment:"进程运行状态" json:"status" xml:"status"`
	Debug        string `db:"debug" bson:"debug" comment:"DEBUG" json:"debug" xml:"debug"`
	Disabled     string `db:"disabled" bson:"disabled" comment:"是否禁用" json:"disabled" xml:"disabled"`
	Created      uint   `db:"created" bson:"created" comment:"创建时间" json:"created" xml:"created"`
	Updated      uint   `db:"updated" bson:"updated" comment:"修改时间" json:"updated" xml:"updated"`
	Error        string `db:"error" bson:"error" comment:"错误信息" json:"error" xml:"error"`
	Lastrun      uint   `db:"lastrun" bson:"lastrun" comment:"上次运行时间" json:"lastrun" xml:"lastrun"`
	Description  string `db:"description" bson:"description" comment:"说明" json:"description" xml:"description"`
	EnableNotify uint   `db:"enable_notify" bson:"enable_notify" comment:"是否启用通知" json:"enable_notify" xml:"enable_notify"`
	NotifyEmail  string `db:"notify_email" bson:"notify_email" comment:"通知人列表" json:"notify_email" xml:"notify_email"`
}

// - base function

func (a *ForeverProcess) Trans() *factory.Transaction {
	return a.base.Trans()
}

func (a *ForeverProcess) Use(trans *factory.Transaction) factory.Model {
	a.base.Use(trans)
	return a
}

func (a *ForeverProcess) SetContext(ctx echo.Context) factory.Model {
	a.base.SetContext(ctx)
	return a
}

func (a *ForeverProcess) Context() echo.Context {
	return a.base.Context()
}

func (a *ForeverProcess) SetConnID(connID int) factory.Model {
	a.base.SetConnID(connID)
	return a
}

func (a *ForeverProcess) SetNamer(namer func(string) string) factory.Model {
	a.base.SetNamer(namer)
	return a
}

func (a *ForeverProcess) Namer() func(string) string {
	return a.base.Namer()
}

func (a *ForeverProcess) SetParam(param *factory.Param) factory.Model {
	a.base.SetParam(param)
	return a
}

func (a *ForeverProcess) Param(mw func(db.Result) db.Result, args ...interface{}) *factory.Param {
	if a.base.Param() == nil {
		return a.NewParam().SetMiddleware(mw).SetArgs(args...)
	}
	return a.base.Param().SetMiddleware(mw).SetArgs(args...)
}

// - current function

func (a *ForeverProcess) New(structName string, connID ...int) factory.Model {
	if len(connID) > 0 {
		return factory.NewModel(structName, connID[0]).Use(a.base.Trans())
	}
	return factory.NewModel(structName, a.base.ConnID()).Use(a.base.Trans())
}

func (a *ForeverProcess) Objects() []*ForeverProcess {
	if a.objects == nil {
		return nil
	}
	return a.objects[:]
}

func (a *ForeverProcess) NewObjects() factory.Ranger {
	return &Slice_ForeverProcess{}
}

func (a *ForeverProcess) InitObjects() *[]*ForeverProcess {
	a.objects = []*ForeverProcess{}
	return &a.objects
}

func (a *ForeverProcess) NewParam() *factory.Param {
	return factory.NewParam(factory.DefaultFactory).SetIndex(a.base.ConnID()).SetTrans(a.base.Trans()).SetCollection(a.Name_()).SetModel(a)
}

func (a *ForeverProcess) Short_() string {
	return "forever_process"
}

func (a *ForeverProcess) Struct_() string {
	return "ForeverProcess"
}

func (a *ForeverProcess) Name_() string {
	if a.base.Namer() != nil {
		return WithPrefix(a.base.Namer()(a.Short_()))
	}
	return WithPrefix(factory.TableNamerGet(a.Short_())(a))
}

func (a *ForeverProcess) CPAFrom(source factory.Model) factory.Model {
	a.SetContext(source.Context())
	a.Use(source.Trans())
	a.SetNamer(source.Namer())
	return a
}

func (a *ForeverProcess) Get(mw func(db.Result) db.Result, args ...interface{}) error {
	base := a.base
	err := a.Param(mw, args...).SetRecv(a).One()
	a.base = base
	return err
}

func (a *ForeverProcess) List(recv interface{}, mw func(db.Result) db.Result, page, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	return a.Param(mw, args...).SetPage(page).SetSize(size).SetRecv(recv).List()
}

func (a *ForeverProcess) GroupBy(keyField string, inputRows ...[]*ForeverProcess) map[string][]*ForeverProcess {
	var rows []*ForeverProcess
	if len(inputRows) > 0 {
		rows = inputRows[0]
	} else {
		rows = a.Objects()
	}
	r := map[string][]*ForeverProcess{}
	for _, row := range rows {
		dmap := row.AsMap()
		vkey := fmt.Sprint(dmap[keyField])
		if _, y := r[vkey]; !y {
			r[vkey] = []*ForeverProcess{}
		}
		r[vkey] = append(r[vkey], row)
	}
	return r
}

func (a *ForeverProcess) KeyBy(keyField string, inputRows ...[]*ForeverProcess) map[string]*ForeverProcess {
	var rows []*ForeverProcess
	if len(inputRows) > 0 {
		rows = inputRows[0]
	} else {
		rows = a.Objects()
	}
	r := map[string]*ForeverProcess{}
	for _, row := range rows {
		dmap := row.AsMap()
		vkey := fmt.Sprint(dmap[keyField])
		r[vkey] = row
	}
	return r
}

func (a *ForeverProcess) AsKV(keyField string, valueField string, inputRows ...[]*ForeverProcess) map[string]interface{} {
	var rows []*ForeverProcess
	if len(inputRows) > 0 {
		rows = inputRows[0]
	} else {
		rows = a.Objects()
	}
	r := map[string]interface{}{}
	for _, row := range rows {
		dmap := row.AsMap()
		vkey := fmt.Sprint(dmap[keyField])
		r[vkey] = dmap[valueField]
	}
	return r
}

func (a *ForeverProcess) ListByOffset(recv interface{}, mw func(db.Result) db.Result, offset, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = a.InitObjects()
	}
	return a.Param(mw, args...).SetOffset(offset).SetSize(size).SetRecv(recv).List()
}

func (a *ForeverProcess) Add() (pk interface{}, err error) {
	a.Created = uint(time.Now().Unix())
	a.Id = 0
	if len(a.Status) == 0 {
		a.Status = "idle"
	}
	if len(a.Debug) == 0 {
		a.Debug = "N"
	}
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	err = DBI.Fire("creating", a, nil)
	if err != nil {
		return
	}
	pk, err = a.Param(nil).SetSend(a).Insert()
	if err == nil && pk != nil {
		if v, y := pk.(uint); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint(v)
		}
	}
	if err == nil {
		err = DBI.Fire("created", a, nil)
	}
	return
}

func (a *ForeverProcess) Edit(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	a.Updated = uint(time.Now().Unix())
	if len(a.Status) == 0 {
		a.Status = "idle"
	}
	if len(a.Debug) == 0 {
		a.Debug = "N"
	}
	if len(a.Disabled) == 0 {
		a.Disabled = "N"
	}
	if err = DBI.Fire("updating", a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(a).Update(); err != nil {
		return
	}
	return DBI.Fire("updated", a, mw, args...)
}

func (a *ForeverProcess) SetField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (err error) {
	return a.SetFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (a *ForeverProcess) SetFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (err error) {

	if val, ok := kvset["status"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["status"] = "idle"
		}
	}
	if val, ok := kvset["debug"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["debug"] = "N"
		}
	}
	if val, ok := kvset["disabled"]; ok && val != nil {
		if v, ok := val.(string); ok && len(v) == 0 {
			kvset["disabled"] = "N"
		}
	}
	m := *a
	m.FromRow(kvset)
	var editColumns []string
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = DBI.FireUpdate("updating", &m, editColumns, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).SetSend(kvset).Update(); err != nil {
		return
	}
	return DBI.FireUpdate("updated", &m, editColumns, mw, args...)
}

func (a *ForeverProcess) Upsert(mw func(db.Result) db.Result, args ...interface{}) (pk interface{}, err error) {
	pk, err = a.Param(mw, args...).SetSend(a).Upsert(func() error {
		a.Updated = uint(time.Now().Unix())
		if len(a.Status) == 0 {
			a.Status = "idle"
		}
		if len(a.Debug) == 0 {
			a.Debug = "N"
		}
		if len(a.Disabled) == 0 {
			a.Disabled = "N"
		}
		return DBI.Fire("updating", a, mw, args...)
	}, func() error {
		a.Created = uint(time.Now().Unix())
		a.Id = 0
		if len(a.Status) == 0 {
			a.Status = "idle"
		}
		if len(a.Debug) == 0 {
			a.Debug = "N"
		}
		if len(a.Disabled) == 0 {
			a.Disabled = "N"
		}
		return DBI.Fire("creating", a, nil)
	})
	if err == nil && pk != nil {
		if v, y := pk.(uint); y {
			a.Id = v
		} else if v, y := pk.(int64); y {
			a.Id = uint(v)
		}
	}
	if err == nil {
		if pk == nil {
			err = DBI.Fire("updated", a, mw, args...)
		} else {
			err = DBI.Fire("created", a, nil)
		}
	}
	return
}

func (a *ForeverProcess) Delete(mw func(db.Result) db.Result, args ...interface{}) (err error) {

	if err = DBI.Fire("deleting", a, mw, args...); err != nil {
		return
	}
	if err = a.Param(mw, args...).Delete(); err != nil {
		return
	}
	return DBI.Fire("deleted", a, mw, args...)
}

func (a *ForeverProcess) Count(mw func(db.Result) db.Result, args ...interface{}) (int64, error) {
	return a.Param(mw, args...).Count()
}

func (a *ForeverProcess) Reset() *ForeverProcess {
	a.Id = 0
	a.Uid = 0
	a.Name = ``
	a.Command = ``
	a.Workdir = ``
	a.Env = ``
	a.Args = ``
	a.Pidfile = ``
	a.Logfile = ``
	a.Errfile = ``
	a.Respawn = 0
	a.Delay = ``
	a.Ping = ``
	a.Pid = 0
	a.Status = ``
	a.Debug = ``
	a.Disabled = ``
	a.Created = 0
	a.Updated = 0
	a.Error = ``
	a.Lastrun = 0
	a.Description = ``
	a.EnableNotify = 0
	a.NotifyEmail = ``
	return a
}

func (a *ForeverProcess) AsMap() map[string]interface{} {
	r := map[string]interface{}{}
	r["Id"] = a.Id
	r["Uid"] = a.Uid
	r["Name"] = a.Name
	r["Command"] = a.Command
	r["Workdir"] = a.Workdir
	r["Env"] = a.Env
	r["Args"] = a.Args
	r["Pidfile"] = a.Pidfile
	r["Logfile"] = a.Logfile
	r["Errfile"] = a.Errfile
	r["Respawn"] = a.Respawn
	r["Delay"] = a.Delay
	r["Ping"] = a.Ping
	r["Pid"] = a.Pid
	r["Status"] = a.Status
	r["Debug"] = a.Debug
	r["Disabled"] = a.Disabled
	r["Created"] = a.Created
	r["Updated"] = a.Updated
	r["Error"] = a.Error
	r["Lastrun"] = a.Lastrun
	r["Description"] = a.Description
	r["EnableNotify"] = a.EnableNotify
	r["NotifyEmail"] = a.NotifyEmail
	return r
}

func (a *ForeverProcess) FromRow(row map[string]interface{}) {
	for key, value := range row {
		switch key {
		case "id":
			a.Id = param.AsUint(value)
		case "uid":
			a.Uid = param.AsUint(value)
		case "name":
			a.Name = param.AsString(value)
		case "command":
			a.Command = param.AsString(value)
		case "workdir":
			a.Workdir = param.AsString(value)
		case "env":
			a.Env = param.AsString(value)
		case "args":
			a.Args = param.AsString(value)
		case "pidfile":
			a.Pidfile = param.AsString(value)
		case "logfile":
			a.Logfile = param.AsString(value)
		case "errfile":
			a.Errfile = param.AsString(value)
		case "respawn":
			a.Respawn = param.AsUint(value)
		case "delay":
			a.Delay = param.AsString(value)
		case "ping":
			a.Ping = param.AsString(value)
		case "pid":
			a.Pid = param.AsInt(value)
		case "status":
			a.Status = param.AsString(value)
		case "debug":
			a.Debug = param.AsString(value)
		case "disabled":
			a.Disabled = param.AsString(value)
		case "created":
			a.Created = param.AsUint(value)
		case "updated":
			a.Updated = param.AsUint(value)
		case "error":
			a.Error = param.AsString(value)
		case "lastrun":
			a.Lastrun = param.AsUint(value)
		case "description":
			a.Description = param.AsString(value)
		case "enable_notify":
			a.EnableNotify = param.AsUint(value)
		case "notify_email":
			a.NotifyEmail = param.AsString(value)
		}
	}
}

func (a *ForeverProcess) Set(key interface{}, value ...interface{}) {
	switch k := key.(type) {
	case map[string]interface{}:
		for kk, vv := range k {
			a.Set(kk, vv)
		}
	default:
		var (
			kk string
			vv interface{}
		)
		if k, y := key.(string); y {
			kk = k
		} else {
			kk = fmt.Sprint(key)
		}
		if len(value) > 0 {
			vv = value[0]
		}
		switch kk {
		case "Id":
			a.Id = param.AsUint(vv)
		case "Uid":
			a.Uid = param.AsUint(vv)
		case "Name":
			a.Name = param.AsString(vv)
		case "Command":
			a.Command = param.AsString(vv)
		case "Workdir":
			a.Workdir = param.AsString(vv)
		case "Env":
			a.Env = param.AsString(vv)
		case "Args":
			a.Args = param.AsString(vv)
		case "Pidfile":
			a.Pidfile = param.AsString(vv)
		case "Logfile":
			a.Logfile = param.AsString(vv)
		case "Errfile":
			a.Errfile = param.AsString(vv)
		case "Respawn":
			a.Respawn = param.AsUint(vv)
		case "Delay":
			a.Delay = param.AsString(vv)
		case "Ping":
			a.Ping = param.AsString(vv)
		case "Pid":
			a.Pid = param.AsInt(vv)
		case "Status":
			a.Status = param.AsString(vv)
		case "Debug":
			a.Debug = param.AsString(vv)
		case "Disabled":
			a.Disabled = param.AsString(vv)
		case "Created":
			a.Created = param.AsUint(vv)
		case "Updated":
			a.Updated = param.AsUint(vv)
		case "Error":
			a.Error = param.AsString(vv)
		case "Lastrun":
			a.Lastrun = param.AsUint(vv)
		case "Description":
			a.Description = param.AsString(vv)
		case "EnableNotify":
			a.EnableNotify = param.AsUint(vv)
		case "NotifyEmail":
			a.NotifyEmail = param.AsString(vv)
		}
	}
}

func (a *ForeverProcess) AsRow() map[string]interface{} {
	r := map[string]interface{}{}
	r["id"] = a.Id
	r["uid"] = a.Uid
	r["name"] = a.Name
	r["command"] = a.Command
	r["workdir"] = a.Workdir
	r["env"] = a.Env
	r["args"] = a.Args
	r["pidfile"] = a.Pidfile
	r["logfile"] = a.Logfile
	r["errfile"] = a.Errfile
	r["respawn"] = a.Respawn
	r["delay"] = a.Delay
	r["ping"] = a.Ping
	r["pid"] = a.Pid
	r["status"] = a.Status
	r["debug"] = a.Debug
	r["disabled"] = a.Disabled
	r["created"] = a.Created
	r["updated"] = a.Updated
	r["error"] = a.Error
	r["lastrun"] = a.Lastrun
	r["description"] = a.Description
	r["enable_notify"] = a.EnableNotify
	r["notify_email"] = a.NotifyEmail
	return r
}

func (a *ForeverProcess) BatchValidate(kvset map[string]interface{}) error {
	if kvset == nil {
		kvset = a.AsRow()
	}
	return factory.BatchValidate(a.Short_(), kvset)
}

func (a *ForeverProcess) Validate(field string, value interface{}) error {
	return factory.Validate(a.Short_(), field, value)
}
